### ISSUE TITLE
Issue with PEP 8

### ISSUE THREAD

**Issue by f77-droid** [GOLOKKU/Graalvm-Java-Install#1]
# Why?
First lets talk about what Python is...

## What is Python?
Python is an interpreted, high-level and general-purpose programming language. Created by Guido van Rossum and first released in 1991, *Python's design philosophy emphasizes* ***code readability*** *with its notable use of significant whitespace.* Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.

## The Issue
- [Spaghetti Code](https://en.wikipedia.org/wiki/Spaghetti_code)
- Do not rely on using system specific commands as compatibility matters
- Unnecessary complication, code can be much much simpler

Thank you for reading my first issue on GitHub, 
and don't ask why I put it here.

**Comment by GOLOKKU** [comment]
I didn't know my code was very bad and hard to read to others :u 
Thanks for cleaning my code :) @f77-droid
